import 'dart:ui';

import 'package:choobietalker/shared/model/google_language.dart';
import 'package:flutter/material.dart';

class Constant {
  List<String> get languageCodes => [
        'arb',
        'cmn-CN',
        'cy-GB',
        'da-DK',
        'de-DE',
        'en-AU',
        'en-GB',
        'en-GB-WLS',
        'en-IN',
        'en-US',
        'es-ES',
        'es-MX',
        'es-US',
        'fr-CA',
        'fr-FR',
        'is-IS',
        'it-IT',
        'ja-JP',
        'hi-IN',
        'ko-KR',
        'nb-NO',
        'nl-NL',
        'pl-PL',
        'pt-BR',
        'pt-PT',
        'ro-RO',
        'ru-RU',
        'sv-SE',
        'tr-TR',
        'en-NZ',
        'en-ZA'
      ];

  List<String> get fonts =>
      ['Roboto', 'Open Sans', 'Montserrat', 'Lato', 'Anton'];

  List<FontWeight> get fontWeights => FontWeight.values;

  List<GoogleLanguage> get googleLanguages =>
      googleLanguageJsonList.map((e) => GoogleLanguage.fromJson(e)).toList();

  List<Map<String, String>> get googleLanguageJsonList => [
        {"name": "Albanian", "code": "sq"},
        {"name": "Arabic", "code": "ar"},
        {"name": "Azerbaijani", "code": "az"},
        {"name": "Basque", "code": "eu"},
        {"name": "Belarusian", "code": "be"},
        {"name": "Bengali", "code": "bn"},
        {"name": "Bulgarian", "code": "bg"},
        {"name": "Catalan", "code": "ca"},
        {"name": "Chinese Simplified", "code": "zh-CN"},
        {"name": "Chinese Traditional", "code": "zh-TW"},
        {"name": "Croatian", "code": "hr"},
        {"name": "Czech", "code": "cs"},
        {"name": "Danish", "code": "da"},
        {"name": "Dutch", "code": "nl"},
        {"name": "English", "code": "en"},
        {"name": "Esperanto", "code": "eo"},
        {"name": "Estonian", "code": "et"},
        {"name": "Filipino", "code": "tl"},
        {"name": "Finnish", "code": "fi"},
        {"name": "French", "code": "fr"},
        {"name": "Galician", "code": "gl"},
        {"name": "Georgian", "code": "ka"},
        {"name": "German", "code": "de"},
        {"name": "Greek", "code": "el"},
        {"name": "Gujarati", "code": "gu"},
        {"name": "Haitian Creole", "code": "ht"},
        {"name": "Hebrew", "code": "iw"},
        {"name": "Hindi", "code": "hi"},
        {"name": "Hungarian", "code": "hu"},
        {"name": "Icelandic", "code": "is"},
        {"name": "Indonesian", "code": "id"},
        {"name": "Irish", "code": "ga"},
        {"name": "Italian", "code": "it"},
        {"name": "Japanese", "code": "ja"},
        {"name": "Kannada", "code": "kn"},
        {"name": "Korean", "code": "ko"},
        {"name": "Latin", "code": "la"},
        {"name": "Latvian", "code": "lv"},
        {"name": "Lithuanian", "code": "lt"},
        {"name": "Macedonian", "code": "mk"},
        {"name": "Malay", "code": "ms"},
        {"name": "Maltese", "code": "mt"},
        {"name": "Norwegian", "code": "no"},
        {"name": "Persian", "code": "fa"},
        {"name": "Polish", "code": "pl"},
        {"name": "Portuguese", "code": "pt"},
        {"name": "Romanian", "code": "ro"},
        {"name": "Russian", "code": "ru"},
        {"name": "Serbian", "code": "sr"},
        {"name": "Slovak", "code": "sk"},
        {"name": "Slovenian", "code": "sl"},
        {"name": "Spanish", "code": "es"},
        {"name": "Swahili", "code": "sw"},
        {"name": "Swedish", "code": "sv"},
        {"name": "Tamil", "code": "ta"},
        {"name": "Telugu", "code": "te"},
        {"name": "Thai", "code": "th"},
        {"name": "Turkish", "code": "tr"},
        {"name": "Ukrainian", "code": "uk"},
        {"name": "Urdu", "code": "ur"},
        {"name": "Vietnamese", "code": "vi"},
        {"name": "Welsh", "code": "cy"},
        {"name": "Yiddish", "code": "yi"}
      ];
  //       {"name": "Irish", "code": "ga"},
  //       {"name": "Albanian", "code": "sq"},
  //       {"name": "Italian", "code": "it"},
  //       {"name": "Arabic", "code": "ar"},
  //       {"name": "Japanese", "code": "ja"},
  //       {"name": "Azerbaijani", "code": "az"},
  //       {"name": "Kannada", "code": "kn"},
  //       {"name": "Basque", "code": "eu"},
  //       {"name": "Korean", "code": "ko"},
  //       {"name": "Bengali", "code": "bn"},
  //       {"name": "Latin", "code": "la"},
  //       {"name": "Belarusian", "code": "be"},
  //       {"name": "Latvian", "code": "lv"},
  //       {"name": "Bulgarian", "code": "bg"},
  //       {"name": "Lithuanian", "code": "lt"},
  //       {"name": "Catalan", "code": "ca"},
  //       {"name": "Macedonian", "code": "mk"},
  //       {"name": "Chinese Simplified", "code": "zh-CN"},
  //       {"name": "Malay", "code": "ms"},
  //       {"name": "Chinese Traditional", "code": "zh-TW"},
  //       {"name": "Maltese", "code": "mt"},
  //       {"name": "Croatian", "code": "hr"},
  //       {"name": "Norwegian", "code": "no"},
  //       {"name": "Czech", "code": "cs"},
  //       {"name": "Persian", "code": "fa"},
  //       {"name": "Danish", "code": "da"},
  //       {"name": "Polish", "code": "pl"},
  //       {"name": "Dutch", "code": "nl"},
  //       {"name": "Portuguese", "code": "pt"},
  //       {"name": "English", "code": "en"},
  //       {"name": "Romanian", "code": "ro"},
  //       {"name": "Esperanto", "code": "eo"},
  //       {"name": "Russian", "code": "ru"},
  //       {"name": "Estonian", "code": "et"},
  //       {"name": "Serbian", "code": "sr"},
  //       {"name": "Filipino", "code": "tl"},
  //       {"name": "Slovak", "code": "sk"},
  //       {"name": "Finnish", "code": "fi"},
  //       {"name": "Slovenian", "code": "sl"},
  //       {"name": "French", "code": "fr"},
  //       {"name": "Spanish", "code": "es"},
  //       {"name": "Galician", "code": "gl"},
  //       {"name": "Swahili", "code": "sw"},
  //       {"name": "Georgian", "code": "ka"},
  //       {"name": "Swedish", "code": "sv"},
  //       {"name": "German", "code": "de"},
  //       {"name": "Tamil", "code": "ta"},
  //       {"name": "Greek", "code": "el"},
  //       {"name": "Telugu", "code": "te"},
  //       {"name": "Gujarati", "code": "gu"},
  //       {"name": "Thai", "code": "th"},
  //       {"name": "Haitian Creole", "code": "ht"},
  //       {"name": "Turkish", "code": "tr"},
  //       {"name": "Hebrew", "code": "iw"},
  //       {"name": "Ukrainian", "code": "uk"},
  //       {"name": "Hindi", "code": "hi"},
  //       {"name": "Urdu", "code": "ur"},
  //       {"name": "Hungarian", "code": "hu"},
  //       {"name": "Vietnamese", "code": "vi"},
  //       {"name": "Icelandic", "code": "is"},
  //       {"name": "Welsh", "code": "cy"},
  //       {"name": "Indonesian", "code": "id"},
  //       {"name": "Yiddish", "code": "yi"},
  //     ];
}
